export const useCountries = () => {
    // 国一覧（抜粋、必要なら全196か国も提供可能）
    const countries = [
        { label: "Aruba", flag: "🇦🇼" },
        { label: "Afghanistan", flag: "🇦🇫" },
        { label: "Angola", flag: "🇦🇴" },
        { label: "Anguilla", flag: "🇦🇮" },
        { label: "Åland Islands", flag: "🇦🇽" },
        { label: "Albania", flag: "🇦🇱" },
        { label: "Andorra", flag: "🇦🇩" },
        { label: "United Arab Emirates", flag: "🇦🇪" },
        { label: "Argentina", flag: "🇦🇷" },
        { label: "Armenia", flag: "🇦🇲" },
        { label: "American Samoa", flag: "🇦🇸" },
        { label: "Antarctica", flag: "🇦🇶" },
        { label: "French Southern Territories", flag: "🇹🇫" },
        { label: "Antigua and Barbuda", flag: "🇦🇬" },
        { label: "Australia", flag: "🇦🇺" },
        { label: "Austria", flag: "🇦🇹" },
        { label: "Azerbaijan", flag: "🇦🇿" },
        { label: "Burundi", flag: "🇧🇮" },
        { label: "Belgium", flag: "🇧🇪" },
        { label: "Benin", flag: "🇧🇯" },
        { label: "Bonaire, Sint Eustatius and Saba", flag: "🇧🇶" },
        { label: "Burkina Faso", flag: "🇧🇫" },
        { label: "Bangladesh", flag: "🇧🇩" },
        { label: "Bulgaria", flag: "🇧🇬" },
        { label: "Bahrain", flag: "🇧🇭" },
        { label: "Bahamas", flag: "🇧🇸" },
        { label: "Bosnia and Herzegovina", flag: "🇧🇦" },
        { label: "Saint Barthélemy", flag: "🇧🇱" },
        { label: "Belarus", flag: "🇧🇾" },
        { label: "Belize", flag: "🇧🇿" },
        { label: "Bermuda", flag: "🇧🇲" },
        { label: "Bolivia, Plurinational State of", flag: "🇧🇴" },
        { label: "Brazil", flag: "🇧🇷" },
        { label: "Barbados", flag: "🇧🇧" },
        { label: "Brunei Darussalam", flag: "🇧🇳" },
        { label: "Bhutan", flag: "🇧🇹" },
        { label: "Bouvet Island", flag: "🇧🇻" },
        { label: "Botswana", flag: "🇧🇼" },
        { label: "Central African Republic", flag: "🇨🇫" },
        { label: "Canada", flag: "🇨🇦" },
        { label: "Cocos (Keeling) Islands", flag: "🇨🇨" },
        { label: "Switzerland", flag: "🇨🇭" },
        { label: "Chile", flag: "🇨🇱" },
        { label: "China", flag: "🇨🇳" },
        { label: "Côte d'Ivoire", flag: "🇨🇮" },
        { label: "Cameroon", flag: "🇨🇲" },
        { label: "Congo, The Democratic Republic of the", flag: "🇨🇩" },
        { label: "Congo", flag: "🇨🇬" },
        { label: "Cook Islands", flag: "🇨🇰" },
        { label: "Colombia", flag: "🇨🇴" },
        { label: "Comoros", flag: "🇰🇲" },
        { label: "Cabo Verde", flag: "🇨🇻" },
        { label: "Costa Rica", flag: "🇨🇷" },
        { label: "Cuba", flag: "🇨🇺" },
        { label: "Curaçao", flag: "🇨🇼" },
        { label: "Christmas Island", flag: "🇨🇽" },
        { label: "Cayman Islands", flag: "🇰🇾" },
        { label: "Cyprus", flag: "🇨🇾" },
        { label: "Czechia", flag: "🇨🇿" },
        { label: "Germany", flag: "🇩🇪" },
        { label: "Djibouti", flag: "🇩🇯" },
        { label: "Dominica", flag: "🇩🇲" },
        { label: "Denmark", flag: "🇩🇰" },
        { label: "Dominican Republic", flag: "🇩🇴" },
        { label: "Algeria", flag: "🇩🇿" },
        { label: "Ecuador", flag: "🇪🇨" },
        { label: "Egypt", flag: "🇪🇬" },
        { label: "Eritrea", flag: "🇪🇷" },
        { label: "Western Sahara", flag: "🇪🇭" },
        { label: "Spain", flag: "🇪🇸" },
        { label: "Estonia", flag: "🇪🇪" },
        { label: "Ethiopia", flag: "🇪🇹" },
        { label: "Finland", flag: "🇫🇮" },
        { label: "Fiji", flag: "🇫🇯" },
        { label: "Falkland Islands (Malvinas)", flag: "🇫🇰" },
        { label: "France", flag: "🇫🇷" },
        { label: "Faroe Islands", flag: "🇫🇴" },
        { label: "Micronesia, Federated States of", flag: "🇫🇲" },
        { label: "Gabon", flag: "🇬🇦" },
        { label: "United Kingdom", flag: "🇬🇧" },
        { label: "Georgia", flag: "🇬🇪" },
        { label: "Guernsey", flag: "🇬🇬" },
        { label: "Ghana", flag: "🇬🇭" },
        { label: "Gibraltar", flag: "🇬🇮" },
        { label: "Guinea", flag: "🇬🇳" },
        { label: "Guadeloupe", flag: "🇬🇵" },
        { label: "Gambia", flag: "🇬🇲" },
        { label: "Guinea-Bissau", flag: "🇬🇼" },
        { label: "Equatorial Guinea", flag: "🇬🇶" },
        { label: "Greece", flag: "🇬🇷" },
        { label: "Grenada", flag: "🇬🇩" },
        { label: "Greenland", flag: "🇬🇱" },
        { label: "Guatemala", flag: "🇬🇹" },
        { label: "French Guiana", flag: "🇬🇫" },
        { label: "Guam", flag: "🇬🇺" },
        { label: "Guyana", flag: "🇬🇾" },
        { label: "Hong Kong", flag: "🇭🇰" },
        { label: "Heard Island and McDonald Islands", flag: "🇭🇲" },
        { label: "Honduras", flag: "🇭🇳" },
        { label: "Croatia", flag: "🇭🇷" },
        { label: "Haiti", flag: "🇭🇹" },
        { label: "Hungary", flag: "🇭🇺" },
        { label: "Indonesia", flag: "🇮🇩" },
        { label: "Isle of Man", flag: "🇮🇲" },
        { label: "India", flag: "🇮🇳" },
        { label: "British Indian Ocean Territory", flag: "🇮🇴" },
        { label: "Ireland", flag: "🇮🇪" },
        { label: "Iran, Islamic Republic of", flag: "🇮🇷" },
        { label: "Iraq", flag: "🇮🇶" },
        { label: "Iceland", flag: "🇮🇸" },
        { label: "Israel", flag: "🇮🇱" },
        { label: "Italy", flag: "🇮🇹" },
        { label: "Jamaica", flag: "🇯🇲" },
        { label: "Jersey", flag: "🇯🇪" },
        { label: "Jordan", flag: "🇯🇴" },
        { label: "Japan", flag: "🇯🇵" },
        { label: "Kazakhstan", flag: "🇰🇿" },
        { label: "Kenya", flag: "🇰🇪" },
        { label: "Kyrgyzstan", flag: "🇰🇬" },
        { label: "Cambodia", flag: "🇰🇭" },
        { label: "Kiribati", flag: "🇰🇮" },
        { label: "Saint Kitts and Nevis", flag: "🇰🇳" },
        { label: "Korea, Republic of", flag: "🇰🇷" },
        { label: "Kuwait", flag: "🇰🇼" },
        { label: "Lao People's Democratic Republic", flag: "🇱🇦" },
        { label: "Lebanon", flag: "🇱🇧" },
        { label: "Liberia", flag: "🇱🇷" },
        { label: "Libya", flag: "🇱🇾" },
        { label: "Saint Lucia", flag: "🇱🇨" },
        { label: "Liechtenstein", flag: "🇱🇮" },
        { label: "Sri Lanka", flag: "🇱🇰" },
        { label: "Lesotho", flag: "🇱🇸" },
        { label: "Lithuania", flag: "🇱🇹" },
        { label: "Luxembourg", flag: "🇱🇺" },
        { label: "Latvia", flag: "🇱🇻" },
        { label: "Macao", flag: "🇲🇴" },
        { label: "Saint Martin (French part)", flag: "🇲🇫" },
        { label: "Morocco", flag: "🇲🇦" },
        { label: "Monaco", flag: "🇲🇨" },
        { label: "Moldova, Republic of", flag: "🇲🇩" },
        { label: "Madagascar", flag: "🇲🇬" },
        { label: "Maldives", flag: "🇲🇻" },
        { label: "Mexico", flag: "🇲🇽" },
        { label: "Marshall Islands", flag: "🇲🇭" },
        { label: "North Macedonia", flag: "🇲🇰" },
        { label: "Mali", flag: "🇲🇱" },
        { label: "Malta", flag: "🇲🇹" },
        { label: "Myanmar", flag: "🇲🇲" },
        { label: "Montenegro", flag: "🇲🇪" },
        { label: "Mongolia", flag: "🇲🇳" },
        { label: "Northern Mariana Islands", flag: "🇲🇵" },
        { label: "Mozambique", flag: "🇲🇿" },
        { label: "Mauritania", flag: "🇲🇷" },
        { label: "Montserrat", flag: "🇲🇸" },
        { label: "Martinique", flag: "🇲🇶" },
        { label: "Mauritius", flag: "🇲🇺" },
        { label: "Malawi", flag: "🇲🇼" },
        { label: "Malaysia", flag: "🇲🇾" },
        { label: "Mayotte", flag: "🇾🇹" },
        { label: "Namibia", flag: "🇳🇦" },
        { label: "New Caledonia", flag: "🇳🇨" },
        { label: "Niger", flag: "🇳🇪" },
        { label: "Norfolk Island", flag: "🇳🇫" },
        { label: "Nigeria", flag: "🇳🇬" },
        { label: "Nicaragua", flag: "🇳🇮" },
        { label: "Niue", flag: "🇳🇺" },
        { label: "Netherlands", flag: "🇳🇱" },
        { label: "Norway", flag: "🇳🇴" },
        { label: "Nepal", flag: "🇳🇵" },
        { label: "Nauru", flag: "🇳🇷" },
        { label: "New Zealand", flag: "🇳🇿" },
        { label: "Oman", flag: "🇴🇲" },
        { label: "Pakistan", flag: "🇵🇰" },
        { label: "Panama", flag: "🇵🇦" },
        { label: "Pitcairn", flag: "🇵🇳" },
        { label: "Peru", flag: "🇵🇪" },
        { label: "Philippines", flag: "🇵🇭" },
        { label: "Palau", flag: "🇵🇼" },
        { label: "Papua New Guinea", flag: "🇵🇬" },
        { label: "Poland", flag: "🇵🇱" },
        { label: "Puerto Rico", flag: "🇵🇷" },
        { label: "Korea, Democratic People's Republic of", flag: "🇰🇵" },
        { label: "Portugal", flag: "🇵🇹" },
        { label: "Paraguay", flag: "🇵🇾" },
        { label: "Palestine, State of", flag: "🇵🇸" },
        { label: "French Polynesia", flag: "🇵🇫" },
        { label: "Qatar", flag: "🇶🇦" },
        { label: "Réunion", flag: "🇷🇪" },
        { label: "Romania", flag: "🇷🇴" },
        { label: "Russian Federation", flag: "🇷🇺" },
        { label: "Rwanda", flag: "🇷🇼" },
        { label: "Saudi Arabia", flag: "🇸🇦" },
        { label: "Sudan", flag: "🇸🇩" },
        { label: "Senegal", flag: "🇸🇳" },
        { label: "Singapore", flag: "🇸🇬" },
        { label: "South Georgia and the South Sandwich Islands", flag: "🇬🇸" },
        { label: "Saint Helena, Ascension and Tristan da Cunha", flag: "🇸🇭" },
        { label: "Svalbard and Jan Mayen", flag: "🇸🇯" },
        { label: "Solomon Islands", flag: "🇸🇧" },
        { label: "Sierra Leone", flag: "🇸🇱" },
        { label: "El Salvador", flag: "🇸🇻" },
        { label: "San Marino", flag: "🇸🇲" },
        { label: "Somalia", flag: "🇸🇴" },
        { label: "Saint Pierre and Miquelon", flag: "🇵🇲" },
        { label: "Serbia", flag: "🇷🇸" },
        { label: "South Sudan", flag: "🇸🇸" },
        { label: "Sao Tome and Principe", flag: "🇸🇹" },
        { label: "Suriname", flag: "🇸🇷" },
        { label: "Slovakia", flag: "🇸🇰" },
        { label: "Slovenia", flag: "🇸🇮" },
        { label: "Sweden", flag: "🇸🇪" },
        { label: "Eswatini", flag: "🇸🇿" },
        { label: "Sint Maarten (Dutch part)", flag: "🇸🇽" },
        { label: "Seychelles", flag: "🇸🇨" },
        { label: "Syrian Arab Republic", flag: "🇸🇾" },
        { label: "Turks and Caicos Islands", flag: "🇹🇨" },
        { label: "Chad", flag: "🇹🇩" },
        { label: "Togo", flag: "🇹🇬" },
        { label: "Thailand", flag: "🇹🇭" },
        { label: "Tajikistan", flag: "🇹🇯" },
        { label: "Tokelau", flag: "🇹🇰" },
        { label: "Turkmenistan", flag: "🇹🇲" },
        { label: "Timor-Leste", flag: "🇹🇱" },
        { label: "Tonga", flag: "🇹🇴" },
        { label: "Trinidad and Tobago", flag: "🇹🇹" },
        { label: "Tunisia", flag: "🇹🇳" },
        { label: "Turkey", flag: "🇹🇷" },
        { label: "Tuvalu", flag: "🇹🇻" },
        { label: "Taiwan, Province of China", flag: "🇹🇼" },
        { label: "Tanzania, United Republic of", flag: "🇹🇿" },
        { label: "Uganda", flag: "🇺🇬" },
        { label: "Ukraine", flag: "🇺🇦" },
        { label: "United States Minor Outlying Islands", flag: "🇺🇲" },
        { label: "Uruguay", flag: "🇺🇾" },
        { label: "United States", flag: "🇺🇸" },
        { label: "Uzbekistan", flag: "🇺🇿" },
        { label: "Holy See (Vatican City State)", flag: "🇻🇦" },
        { label: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
        { label: "Venezuela, Bolivarian Republic of", flag: "🇻🇪" },
        { label: "Virgin Islands, British", flag: "🇻🇬" },
        { label: "Virgin Islands, U.S.", flag: "🇻🇮" },
        { label: "Viet Nam", flag: "🇻🇳" },
        { label: "Vanuatu", flag: "🇻🇺" },
        { label: "Wallis and Futuna", flag: "🇼🇫" },
        { label: "Samoa", flag: "🇼🇸" },
        { label: "Yemen", flag: "🇾🇪" },
        { label: "South Africa", flag: "🇿🇦" },
        { label: "Zambia", flag: "🇿🇲" },
        { label: "Zimbabwe", flag: "🇿🇼" },
    ];

    return { countries };
};
