import { getFirestore, doc, updateDoc, serverTimestamp } from 'firebase/firestore'
export const useCountries = () => {
  const countries = [
    { label: "Afghanistan", flag: "🇦🇫", code: "AF" },
    { label: "Albania", flag: "🇦🇱", code: "AL" },
    { label: "Algeria", flag: "🇩🇿", code: "DZ" },
    { label: "Andorra", flag: "🇦🇩", code: "AD" },
    { label: "Angola", flag: "🇦🇴", code: "AO" },
    { label: "Antigua and Barbuda", flag: "🇦🇬", code: "AG" },
    { label: "Argentina", flag: "🇦🇷", code: "AR" },
    { label: "Armenia", flag: "🇦🇲", code: "AM" },
    { label: "Australia", flag: "🇦🇺", code: "AU" },
    { label: "Austria", flag: "🇦🇹", code: "AT" },
    { label: "Azerbaijan", flag: "🇦🇿", code: "AZ" },
    { label: "Bahamas", flag: "🇧🇸", code: "BS" },
    { label: "Bahrain", flag: "🇧🇭", code: "BH" },
    { label: "Bangladesh", flag: "🇧🇩", code: "BD" },
    { label: "Barbados", flag: "🇧🇧", code: "BB" },
    { label: "Belarus", flag: "🇧🇾", code: "BY" },
    { label: "Belgium", flag: "🇧🇪", code: "BE" },
    { label: "Belize", flag: "🇧🇿", code: "BZ" },
    { label: "Benin", flag: "🇧🇯", code: "BJ" },
    { label: "Bhutan", flag: "🇧🇹", code: "BT" },
    { label: "Bolivia", flag: "🇧🇴", code: "BO" },
    { label: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA" },
    { label: "Botswana", flag: "🇧🇼", code: "BW" },
    { label: "Brazil", flag: "🇧🇷", code: "BR" },
    { label: "Brunei", flag: "🇧🇳", code: "BN" },
    { label: "Bulgaria", flag: "🇧🇬", code: "BG" },
    { label: "Burkina Faso", flag: "🇧🇫", code: "BF" },
    { label: "Burundi", flag: "🇧🇮", code: "BI" },
    { label: "Cabo Verde", flag: "🇨🇻", code: "CV" },
    { label: "Cambodia", flag: "🇰🇭", code: "KH" },
    { label: "Cameroon", flag: "🇨🇲", code: "CM" },
    { label: "Canada", flag: "🇨🇦", code: "CA" },
    { label: "Central African Republic", flag: "🇨🇫", code: "CF" },
    { label: "Chad", flag: "🇹🇩", code: "TD" },
    { label: "Chile", flag: "🇨🇱", code: "CL" },
    { label: "China", flag: "🇨🇳", code: "CN" },
    { label: "Colombia", flag: "🇨🇴", code: "CO" },
    { label: "Comoros", flag: "🇰🇲", code: "KM" },
    { label: "Congo (Brazzaville)", flag: "🇨🇬", code: "CG" },
    { label: "Congo (Kinshasa)", flag: "🇨🇩", code: "CD" },
    { label: "Costa Rica", flag: "🇨🇷", code: "CR" },
    { label: "Croatia", flag: "🇭🇷", code: "HR" },
    { label: "Cuba", flag: "🇨🇺", code: "CU" },
    { label: "Cyprus", flag: "🇨🇾", code: "CY" },
    { label: "Czech Republic", flag: "🇨🇿", code: "CZ" },
    { label: "Denmark", flag: "🇩🇰", code: "DK" },
    { label: "Djibouti", flag: "🇩🇯", code: "DJ" },
    { label: "Dominica", flag: "🇩🇲", code: "DM" },
    { label: "Dominican Republic", flag: "🇩🇴", code: "DO" },
    { label: "Ecuador", flag: "🇪🇨", code: "EC" },
    { label: "Egypt", flag: "🇪🇬", code: "EG" },
    { label: "El Salvador", flag: "🇸🇻", code: "SV" },
    { label: "Equatorial Guinea", flag: "🇬🇶", code: "GQ" },
    { label: "Eritrea", flag: "🇪🇷", code: "ER" },
    { label: "Estonia", flag: "🇪🇪", code: "EE" },
    { label: "Eswatini", flag: "🇸🇿", code: "SZ" },
    { label: "Ethiopia", flag: "🇪🇹", code: "ET" },
    { label: "Fiji", flag: "🇫🇯", code: "FJ" },
    { label: "Finland", flag: "🇫🇮", code: "FI" },
    { label: "France", flag: "🇫🇷", code: "FR" },
    { label: "Gabon", flag: "🇬🇦", code: "GA" },
    { label: "Gambia", flag: "🇬🇲", code: "GM" },
    { label: "Georgia", flag: "🇬🇪", code: "GE" },
    { label: "Germany", flag: "🇩🇪", code: "DE" },
    { label: "Ghana", flag: "🇬🇭", code: "GH" },
    { label: "Greece", flag: "🇬🇷", code: "GR" },
    { label: "Grenada", flag: "🇬🇩", code: "GD" },
    { label: "Guatemala", flag: "🇬🇹", code: "GT" },
    { label: "Guinea", flag: "🇬🇳", code: "GN" },
    { label: "Guinea-Bissau", flag: "🇬🇼", code: "GW" },
    { label: "Guyana", flag: "🇬🇾", code: "GY" },
    { label: "Haiti", flag: "🇭🇹", code: "HT" },
    { label: "Honduras", flag: "🇭🇳", code: "HN" },
    { label: "Hungary", flag: "🇭🇺", code: "HU" },
    { label: "Iceland", flag: "🇮🇸", code: "IS" },
    { label: "India", flag: "🇮🇳", code: "IN" },
    { label: "Indonesia", flag: "🇮🇩", code: "ID" },
    { label: "Iran", flag: "🇮🇷", code: "IR" },
    { label: "Iraq", flag: "🇮🇶", code: "IQ" },
    { label: "Ireland", flag: "🇮🇪", code: "IE" },
    { label: "Israel", flag: "🇮🇱", code: "IL" },
    { label: "Italy", flag: "🇮🇹", code: "IT" },
    { label: "Jamaica", flag: "🇯🇲", code: "JM" },
    { label: "Japan", flag: "🇯🇵", code: "JP" },
    { label: "Jordan", flag: "🇯🇴", code: "JO" },
    { label: "Kazakhstan", flag: "🇰🇿", code: "KZ" },
    { label: "Kenya", flag: "🇰🇪", code: "KE" },
    { label: "Kiribati", flag: "🇰🇮", code: "KI" },
    { label: "Korea, North", flag: "🇰🇵", code: "KP" },
    { label: "Korea, South", flag: "🇰🇷", code: "KR" },
    { label: "Kuwait", flag: "🇰🇼", code: "KW" },
    { label: "Kyrgyzstan", flag: "🇰🇬", code: "KG" },
    { label: "Laos", flag: "🇱🇦", code: "LA" },
    { label: "Latvia", flag: "🇱🇻", code: "LV" },
    { label: "Lebanon", flag: "🇱🇧", code: "LB" },
    { label: "Lesotho", flag: "🇱🇸", code: "LS" },
    { label: "Liberia", flag: "🇱🇷", code: "LR" },
    { label: "Libya", flag: "🇱🇾", code: "LY" },
    { label: "Liechtenstein", flag: "🇱🇮", code: "LI" },
    { label: "Lithuania", flag: "🇱🇹", code: "LT" },
    { label: "Luxembourg", flag: "🇱🇺", code: "LU" },
    { label: "Madagascar", flag: "🇲🇬", code: "MG" },
    { label: "Malawi", flag: "🇲🇼", code: "MW" },
    { label: "Malaysia", flag: "🇲🇾", code: "MY" },
    { label: "Maldives", flag: "🇲🇻", code: "MV" },
    { label: "Mali", flag: "🇲🇱", code: "ML" },
    { label: "Malta", flag: "🇲🇹", code: "MT" },
    { label: "Marshall Islands", flag: "🇲🇭", code: "MH" },
    { label: "Mauritania", flag: "🇲🇷", code: "MR" },
    { label: "Mauritius", flag: "🇲🇺", code: "MU" },
    { label: "Mexico", flag: "🇲🇽", code: "MX" },
    { label: "Micronesia", flag: "🇫🇲", code: "FM" },
    { label: "Moldova", flag: "🇲🇩", code: "MD" },
    { label: "Monaco", flag: "🇲🇨", code: "MC" },
    { label: "Mongolia", flag: "🇲🇳", code: "MN" },
    { label: "Montenegro", flag: "🇲🇪", code: "ME" },
    { label: "Morocco", flag: "🇲🇦", code: "MA" },
    { label: "Mozambique", flag: "🇲🇿", code: "MZ" },
    { label: "Myanmar", flag: "🇲🇲", code: "MM" },
    { label: "Namibia", flag: "🇳🇦", code: "NA" },
    { label: "Nauru", flag: "🇳🇷", code: "NR" },
    { label: "Nepal", flag: "🇳🇵", code: "NP" },
    { label: "Netherlands", flag: "🇳🇱", code: "NL" },
    { label: "New Zealand", flag: "🇳🇿", code: "NZ" },
    { label: "Nicaragua", flag: "🇳🇮", code: "NI" },
    { label: "Niger", flag: "🇳🇪", code: "NE" },
    { label: "Nigeria", flag: "🇳🇬", code: "NG" },
    { label: "North Macedonia", flag: "🇲🇰", code: "MK" },
    { label: "Norway", flag: "🇳🇴", code: "NO" },
    { label: "Oman", flag: "🇴🇲", code: "OM" },
    { label: "Pakistan", flag: "🇵🇰", code: "PK" },
    { label: "Palau", flag: "🇵🇼", code: "PW" },
    { label: "Panama", flag: "🇵🇦", code: "PA" },
    { label: "Papua New Guinea", flag: "🇵🇬", code: "PG" },
    { label: "Paraguay", flag: "🇵🇾", code: "PY" },
    { label: "Peru", flag: "🇵🇪", code: "PE" },
    { label: "Philippines", flag: "🇵🇭", code: "PH" },
    { label: "Poland", flag: "🇵🇱", code: "PL" },
    { label: "Portugal", flag: "🇵🇹", code: "PT" },
    { label: "Qatar", flag: "🇶🇦", code: "QA" },
    { label: "Romania", flag: "🇷🇴", code: "RO" },
    { label: "Russia", flag: "🇷🇺", code: "RU" },
    { label: "Rwanda", flag: "🇷🇼", code: "RW" },
    { label: "Saint Kitts and Nevis", flag: "🇰🇳", code: "KN" },
    { label: "Saint Lucia", flag: "🇱🇨", code: "LC" },
    { label: "Saint Vincent and the Grenadines", flag: "🇻🇨", code: "VC" },
    { label: "Samoa", flag: "🇼🇸", code: "WS" },
    { label: "San Marino", flag: "🇸🇲", code: "SM" },
    { label: "Sao Tome and Principe", flag: "🇸🇹", code: "ST" },
    { label: "Saudi Arabia", flag: "🇸🇦", code: "SA" },
    { label: "Senegal", flag: "🇸🇳", code: "SN" },
    { label: "Serbia", flag: "🇷🇸", code: "RS" },
    { label: "Seychelles", flag: "🇸🇨", code: "SC" },
    { label: "Sierra Leone", flag: "🇸🇱", code: "SL" },
    { label: "Singapore", flag: "🇸🇬", code: "SG" },
    { label: "Slovakia", flag: "🇸🇰", code: "SK" },
    { label: "Slovenia", flag: "🇸🇮", code: "SI" },
    { label: "Solomon Islands", flag: "🇸🇧", code: "SB" },
    { label: "Somalia", flag: "🇸🇴", code: "SO" },
    { label: "South Africa", flag: "🇿🇦", code: "ZA" },
    { label: "South Sudan", flag: "🇸🇸", code: "SS" },
    { label: "Spain", flag: "🇪🇸", code: "ES" },
    { label: "Sri Lanka", flag: "🇱🇰", code: "LK" },
    { label: "Sudan", flag: "🇸🇩", code: "SD" },
    { label: "Suriname", flag: "🇸🇷", code: "SR" },
    { label: "Sweden", flag: "🇸🇪", code: "SE" },
    { label: "Switzerland", flag: "🇨🇭", code: "CH" },
    { label: "Syria", flag: "🇸🇾", code: "SY" },
    { label: "Taiwan", flag: "🇹🇼", code: "TW" },
    { label: "Tajikistan", flag: "🇹🇯", code: "TJ" },
    { label: "Tanzania", flag: "🇹🇿", code: "TZ" },
    { label: "Thailand", flag: "🇹🇭", code: "TH" },
    { label: "Timor-Leste", flag: "🇹🇱", code: "TL" },
    { label: "Togo", flag: "🇹🇬", code: "TG" },
    { label: "Tonga", flag: "🇹🇴", code: "TO" },
    { label: "Trinidad and Tobago", flag: "🇹🇹", code: "TT" },
    { label: "Tunisia", flag: "🇹🇳", code: "TN" },
    { label: "Turkey", flag: "🇹🇷", code: "TR" },
    { label: "Turkmenistan", flag: "🇹🇲", code: "TM" },
    { label: "Tuvalu", flag: "🇹🇻", code: "TV" },
    { label: "Uganda", flag: "🇺🇬", code: "UG" },
    { label: "Ukraine", flag: "🇺🇦", code: "UA" },
    { label: "United Arab Emirates", flag: "🇦🇪", code: "AE" },
    { label: "United Kingdom", flag: "🇬🇧", code: "GB" },
    { label: "United States", flag: "🇺🇸", code: "US" },
    { label: "Uruguay", flag: "🇺🇾", code: "UY" },
    { label: "Uzbekistan", flag: "🇺🇿", code: "UZ" },
    { label: "Vanuatu", flag: "🇻🇺", code: "VU" },
    { label: "Venezuela", flag: "🇻🇪", code: "VE" },
    { label: "Vietnam", flag: "🇻🇳", code: "VN" },
    { label: "Yemen", flag: "🇾🇪", code: "YE" },
    { label: "Zambia", flag: "🇿🇲", code: "ZM" },
    { label: "Zimbabwe", flag: "🇿🇼", code: "ZW" },
  ];

  return { countries };
};

export async function updateUserNation(uid: string, nation: string) {
  const db = getFirestore()
  const ref = doc(db, 'users', uid)
  await updateDoc(ref, { nation, updatedAt: serverTimestamp() })
}